spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: example-service
          uri: http://localhost:8200
          predicates:
            - Path=/example

server:
  port: 8762

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/discovery/


