spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: example-service
          uri: http://localhost:8200
          predicates:
            - Path=/example
        - id: auth-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=false
            - RemoveRequestHeader=Cookie,Set-Cookie

server:
  port: 8762

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/discovery/


